services:
  - type: web
    name: groq-legal-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GROQ_API_KEY
        value: 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
